WIP: Feat/dob 73 refactoring for multi client capability
virtualidentityag/diakonie-onlineBeratung-mailService pull request #3
Opened 2021-04-27 14:31 UTC by Schweizer-Philipp

2021-05-06 15:53 UTC, PepeCortisona requested changes

2021-05-06 15:53 UTC, PepeCortisona commented on src/main/java/de/caritas/cob/mailservice/config/ThymeleafConfig.java
>     * @return ClassLoaderTemplateResolver.
This documentation seems to be wrong after the changes underneath

2021-05-06 15:53 UTC, PepeCortisona commented on src/main/java/de/caritas/cob/mailservice/api/service/SmtpMailService.java
> +          InputStreamSource inputStreamSource = newResources ? new ByteArrayResource(
this block is not read friendly. And is it really necessary to work with old and new location? cannot we refactor, so that there is only one? or at least name them case oriented (e.g., default, custom)

2021-05-06 15:53 UTC, PepeCortisona commented on src/main/resources/application.properties
> +spring.mail.username=xx
please don't commit dummy values in here

2021-05-06 15:53 UTC, PepeCortisona commented on src/main/resources/application.properties
> +csrf.header.property=test
please don't commit dummy values in here

2021-05-06 15:53 UTC, PepeCortisona commented on src/main/resources/application.properties
> +server.port=8081
please validate if this change has to be committed and if so, what the implications are

2021-05-06 15:53 UTC, PepeCortisona commented on src/main/resources/application.properties
> +caritas.base.url=http://onlineberatung.local
please check the implications and document any needed changes for Caritas environments

2021-05-06 15:53 UTC, PepeCortisona commented on src/main/resources/application.properties
> +resourcePath=/Users/philipp.schweizer/Documents/Work/Diakonie/diakonie-onlineBeratung-mailService/templates/
don't commit such values. make sure this operations (adding new properties) are well documented for running environments

2021-05-11 14:49 UTC, PepeCortisona approved these changes

2021-05-12 06:27 UTC, daho4b commented on src/main/java/de/caritas/cob/mailservice/api/service/ExchangeMailService.java
> +                  customResourcePath + CUSTOM_TEMPLATE_IMAGE_DIR + templateImage.getFilename()) : getClass()
Please check sonar issue

2021-05-12 06:59 UTC, daho4b commented on src/main/java/de/caritas/cob/mailservice/api/service/SmtpMailService.java
Please check Sonar issues in this class

2021-05-12 07:07 UTC, daho4b commented on src/main/java/de/caritas/cob/mailservice/api/service/TemplateDescriptionService.java
>  import com.fasterxml.jackson.databind.ObjectMapper;
Please check sonar issues in this file

2021-05-12 07:13 UTC, daho4b requested changes
See comments

2021-05-12 12:46 UTC, daho4b approved these changes

2021-05-12 12:46 UTC, merged