feat: provide theming for email templates
virtualidentityag/diakonie-onlineBeratung-mailService pull request #5
Opened 2021-06-01 13:00 UTC by amannn

Adjusts the existing templates to match the Diakonie branding. The changes are rather minimal but we should test all email templates eventually.

2021-06-02 07:53 UTC, koepferd requested changes

2021-06-02 07:53 UTC, koepferd commented on templates/enquiry-notification-consultant.html
> +                       Ihr Caritas Team
This should be `Diakonie`.

2021-06-02 07:53 UTC, koepferd commented on templates/message-notification-asker.html
> +                       Ihr Caritas Team<br/>
This should be `Diakonie`

2021-06-02 07:54 UTC, koepferd commented
Open todos:

- [ ] await testing next week
- [ ] discuss integration of the templates (overwriting default files)

2021-06-02 09:48 UTC, koepferd approved these changes

2021-06-17 12:34 UTC, amannn commented on templates/assign-enquiry-notification.html
> +                     <a href=''><img style='width: 40px; height: 40px;' src='cid:logo.png'/></a>
On Gmail Android the logo can overflow (same as with Caritas):

![signal-2021-06-17-143340](https://user-images.githubusercontent.com/4038316/122397223-0eba1280-cf79-11eb-9fb6-6ac974cc4be4.png)

2021-06-17 12:36 UTC, amannn commented
Gmail web and GMX looks good to me.

Gmail:

<img width="840" alt="Screenshot 2021-06-17 at 14 35 17" src="https://user-images.githubusercontent.com/4038316/122397538-59d42580-cf79-11eb-9c7e-4792af07d8e2.png">


GMX:

<img width="558" alt="Screenshot 2021-06-17 at 14 35 06" src="https://user-images.githubusercontent.com/4038316/122397469-4a54dc80-cf79-11eb-94f6-c8ddc2c0bb79.png">

2021-06-17 13:01 UTC, koepferd commented
Additionally to the logo overflow I have another issue on Android > Gmail App (Web Version is fine after accepting showing images) - only a part of the images are loaded:

![photo_2021-06-17_14-55-44](https://user-images.githubusercontent.com/8968377/122400837-60b06780-cf7c-11eb-9657-94d5d9927811.jpg)

Outlooks looks fine: Outlook Web on Android and Mac, Outlook App on Mac

2021-06-17 14:10 UTC, daho4b commented
![image](https://user-images.githubusercontent.com/62099612/122412873-39f72e80-cf86-11eb-9d52-23af3076915d.png)

different distance between text and greeting

2021-06-17 14:16 UTC, daho4b commented
![image](https://user-images.githubusercontent.com/62099612/122414189-3d3eea00-cf87-11eb-9e0f-f01aa20af96b.png)

no images are displayed (all-inkl webmail)

2021-06-18 06:32 UTC, koepferd commented
I don't think the not showing images are general bugs. I checked the same mails again this morning and the images are loading - the client may load images depending on internet connection?

2021-06-21 07:25 UTC, amannn commented
We discussed this PR in the daily today. The frontend part is finished and will be moved by @PepeCortisona to the right place. If I can help with something, please let me know!

2021-12-03 12:45 UTC, merged